# SPDX-License-Identifier: Apache-2.0
"""Admin panel routes for Fusion-MLX server configuration.

This module provides HTTP routes for the admin panel including:
- Login/logout with API key authentication
- Dashboard for server monitoring
- Model settings management (per-model sampling parameters, pinning, default)
- Global settings management
"""

import logging
import time
from dataclasses import asdict, is_dataclass

from fastapi import APIRouter, Depends, HTTPException

from .auth import (
    require_admin,
)

logger = logging.getLogger(__name__)

PRESET_REMOTE_URL = "http://bench.dpdns.org/assets/fusionmlx_preset.json"


from .helpers import (
    _get_engine_pool,
    _get_global_settings,
    _get_rich_global_settings,
    _get_server_state,
    _get_settings_manager,
)
from .models import (
    CacheProbeRequest,
)

_router = APIRouter()

# =============================================================================
# Stats API Routes
# =============================================================================


def _get_engine_info() -> dict:
    """Get commit SHA and GitHub URL for engine packages.

    Fallback chain:
    1. PEP 610 direct_url.json (pip install git+https://...)
    2. _engine_commits.json (generated by build.py for app bundle)
    3. Parse pyproject.toml at runtime (dev environment)
    """
    import importlib.metadata

    engines = {}
    packages = {
        "mlx-lm": "https://github.com/ml-explore/mlx-lm",
        "mlx-vlm": "https://github.com/Blaizzy/mlx-vlm",
        "mlx-embeddings": "https://github.com/Blaizzy/mlx-embeddings",
        "mlx-audio": "https://github.com/Blaizzy/mlx-audio",
    }

    fallback_commits = _load_fallback_commits(packages)

    for pkg_name, default_url in packages.items():
        info = {"name": pkg_name, "version": None, "commit": None, "url": None}
        try:
            dist = importlib.metadata.distribution(pkg_name)
            info["version"] = dist.version

            # Method 1: PEP 610 direct_url.json
            commit_info = _get_commit_from_direct_url(dist, default_url)
            if not commit_info:
                # Methods 2+3: _engine_commits.json or pyproject.toml
                commit_info = fallback_commits.get(pkg_name)

            if commit_info:
                info["commit"] = commit_info["commit"]
                info["url"] = commit_info["url"]
        except Exception:
            pass
        engines[pkg_name] = info

    return engines


def _get_commit_from_direct_url(dist, default_url: str) -> dict | None:
    """Extract commit SHA from PEP 610 direct_url.json."""
    import json

    try:
        direct_url_text = dist.read_text("direct_url.json")
        if direct_url_text:
            direct_url = json.loads(direct_url_text)
            vcs_info = direct_url.get("vcs_info", {})
            commit = vcs_info.get("commit_id")
            if commit:
                repo_url = direct_url.get("url", default_url).rstrip("/")
                if repo_url.endswith(".git"):
                    repo_url = repo_url[:-4]
                return {"commit": commit, "url": f"{repo_url}/commit/{commit}"}
    except Exception:
        pass
    return None


def _load_fallback_commits(packages: dict[str, str]) -> dict:
    """Load commit SHAs from fallback sources.

    Tries in order:
    1. _engine_commits.json (generated by build.py, lives in fusion_mlx package dir)
    2. pyproject.toml (dev environment, lives one level above package dir)
    """
    import json
    from pathlib import Path

    # This file is at fusion_mlx/admin/routes.py → package dir is fusion_mlx/
    pkg_dir = Path(__file__).resolve().parent.parent

    # Method 2: _engine_commits.json (written by build.py for app bundle)
    commits_file = pkg_dir / "_engine_commits.json"
    if commits_file.is_file():
        try:
            data = json.loads(commits_file.read_text())
            result = {}
            for pkg_name, entry in data.items():
                if isinstance(entry, dict) and "commit" in entry:
                    commit = entry["commit"]
                    repo_url = entry.get("url", packages.get(pkg_name, ""))
                    if "/commit/" not in repo_url:
                        repo_url = f"{repo_url}/commit/{commit}"
                    result[pkg_name] = {"commit": commit, "url": repo_url}
            if result:
                return result
        except Exception:
            pass

    # Method 3: Parse pyproject.toml (dev environment)
    pyproject = pkg_dir.parent / "pyproject.toml"
    if pyproject.is_file():
        try:
            return _parse_commits_from_pyproject(pyproject, packages)
        except Exception:
            pass

    return {}


def _parse_commits_from_pyproject(pyproject_path, packages: dict[str, str]) -> dict:
    """Extract commit SHAs from git+https:// URLs in pyproject.toml."""
    import re
    from pathlib import Path

    content = Path(pyproject_path).read_text()
    commits = {}
    # Match: "mlx-lm @ git+https://github.com/.../mlx-lm@<sha>"
    pattern = r'"(\S+)\s*@\s*git\+https://[^@"]+@([0-9a-f]{7,40})"'
    for match in re.finditer(pattern, content):
        pkg_name = match.group(1).strip().lower()
        sha = match.group(2)
        if pkg_name in packages:
            repo_url = packages[pkg_name]
            commits[pkg_name] = {
                "commit": sha,
                "url": f"{repo_url}/commit/{sha}",
            }
    return commits


def _build_runtime_cache_observability(
    global_settings,
    model_filter: str = "",
) -> dict:
    """Build runtime cache observability payload for dashboard.

    Includes the effective runtime paths and per-model SSD cache runtime stats
    from loaded schedulers, so users can verify real cache state without manual
    process inspection.
    """
    if global_settings is None:
        return {
            "base_path": "",
            "ssd_cache_dir": "",
            "response_state_dir": "",
            "models": [],
            "total_num_files": 0,
            "total_size_bytes": 0,
            "effective_block_sizes": [],
            "hot_cache_max_bytes": 0,
            "hot_cache_size_bytes": 0,
            "hot_cache_entries": 0,
        }

    cache_dir = global_settings.cache.get_ssd_cache_dir(global_settings.base_path)
    cache_cfg = global_settings.cache
    try:
        cfg_disk_max = cache_cfg.get_ssd_cache_max_size_bytes(global_settings.base_path)
    except (ValueError, OSError, TypeError) as exc:
        logger.warning("Could not read SSD cache max size from config: %s", exc)
        cfg_disk_max = 0

    payload = {
        "base_path": str(global_settings.base_path),
        "ssd_cache_dir": str(cache_dir),
        "response_state_dir": str(cache_dir / "response-state"),
        "models": [],
        "total_num_files": 0,
        "total_size_bytes": 0,
        "effective_block_sizes": [],
        "disk_max_bytes": cfg_disk_max,
        "hot_cache_max_bytes": 0,
        "hot_cache_size_bytes": 0,
        "hot_cache_entries": 0,
    }

    engine_pool = _get_engine_pool()
    if engine_pool is None:
        return payload

    block_sizes = set()

    for model_info in engine_pool.get_status().get("models", []):
        model_id = model_info.get("id")
        if not model_id:
            continue
        if model_filter and model_id != model_filter:
            continue
        if not model_info.get("loaded"):
            continue

        entry = engine_pool._entries.get(model_id)
        if entry is None or entry.engine is None:
            continue

        async_core = getattr(entry.engine, "_engine", None)
        core = getattr(async_core, "engine", None) if async_core is not None else None
        scheduler = getattr(core, "scheduler", None) if core is not None else None

        runtime_stats = None
        if scheduler is not None and hasattr(scheduler, "get_ssd_cache_stats"):
            try:
                runtime_stats = scheduler.get_ssd_cache_stats()
            except Exception as exc:
                logger.warning(
                    "Failed to collect runtime cache stats for model '%s': %s",
                    model_id,
                    exc,
                )
                continue

        if not runtime_stats:
            continue

        block_size = runtime_stats.get("block_size")
        indexed_blocks = runtime_stats.get("indexed_blocks")

        ssd_stats = runtime_stats.get("ssd_cache")
        if is_dataclass(ssd_stats):
            ssd_stats = asdict(ssd_stats)
        elif hasattr(ssd_stats, "to_dict"):
            ssd_stats = ssd_stats.to_dict()
        elif not isinstance(ssd_stats, dict):
            ssd_stats = {}

        ssd_manager = getattr(scheduler, "paged_ssd_cache_manager", None)
        scheduler_model_name = getattr(
            getattr(scheduler, "config", None), "model_name", ""
        )
        if ssd_manager is not None and hasattr(ssd_manager, "get_stats_for_model"):
            try:
                scoped_ssd_stats = ssd_manager.get_stats_for_model(
                    scheduler_model_name or model_id
                )
                if is_dataclass(scoped_ssd_stats):
                    ssd_stats = asdict(scoped_ssd_stats)
                elif isinstance(scoped_ssd_stats, dict):
                    ssd_stats = scoped_ssd_stats
            except Exception as exc:
                logger.warning(
                    "Failed to collect model-scoped SSD cache stats for model '%s': %s",
                    model_id,
                    exc,
                )

        prefix_stats = runtime_stats.get("prefix_cache")
        if is_dataclass(prefix_stats):
            prefix_stats = asdict(prefix_stats)
        elif hasattr(prefix_stats, "to_dict"):
            prefix_stats = prefix_stats.to_dict()
        elif not isinstance(prefix_stats, dict):
            prefix_stats = {}

        indexed_blocks_value = indexed_blocks if isinstance(indexed_blocks, int) else 0
        if not isinstance(block_size, int) or block_size <= 0:
            block_size = int(prefix_stats.get("block_size", 0) or 0)

        partial_block_skips = int(prefix_stats.get("partial_block_skips", 0) or 0)
        partial_tokens_skipped = int(prefix_stats.get("partial_tokens_skipped", 0) or 0)
        last_partial_tokens_skipped = int(
            prefix_stats.get("last_partial_tokens_skipped", 0) or 0
        )
        last_tokens_to_next_block = int(
            prefix_stats.get("last_tokens_to_next_block", 0) or 0
        )

        has_sub_block_cache = (
            indexed_blocks_value == 0
            and isinstance(block_size, int)
            and block_size > 0
            and partial_block_skips > 0
        )

        model_payload = {
            "id": model_id,
            "block_size": block_size,
            "indexed_blocks": indexed_blocks_value,
            "indexed_blocks_display": (
                f"<{block_size}" if has_sub_block_cache else str(indexed_blocks_value)
            ),
            "has_sub_block_cache": has_sub_block_cache,
            "partial_block_skips": partial_block_skips,
            "partial_tokens_skipped": partial_tokens_skipped,
            "last_partial_tokens_skipped": last_partial_tokens_skipped,
            "last_tokens_to_next_block": last_tokens_to_next_block,
            "num_files": int(ssd_stats.get("num_files", 0) or 0),
            "total_size_bytes": int(ssd_stats.get("total_size_bytes", 0) or 0),
            "max_size_bytes": int(ssd_stats.get("max_size_bytes", 0) or 0),
            "hot_cache_max_bytes": int(ssd_stats.get("hot_cache_max_bytes", 0) or 0),
            "hot_cache_size_bytes": int(ssd_stats.get("hot_cache_size_bytes", 0) or 0),
            "hot_cache_entries": int(ssd_stats.get("hot_cache_entries", 0) or 0),
        }

        cache_rates = runtime_stats.get("cache_rates")
        if cache_rates:
            model_payload["cache_rates"] = cache_rates

        payload["models"].append(model_payload)
        payload["total_num_files"] += model_payload["num_files"]
        payload["total_size_bytes"] += model_payload["total_size_bytes"]

        if isinstance(block_size, int) and block_size > 0:
            block_sizes.add(block_size)

    payload["effective_block_sizes"] = sorted(block_sizes)

    # Aggregate hot-cache and disk-max across models.
    # hot_cache_max sums across models (each model reserves its own slice of
    # the same process-wide hot cache budget) so the gauge denominator matches
    # the summed numerator.  disk_max keeps the config fallback via max()
    # because a single SSD cache directory is shared — the effective cap is
    # the largest configured limit, not a per-model sum.
    hot_cache_max = 0
    disk_max = payload["disk_max_bytes"]
    hot_cache_size_total = 0
    hot_cache_entries_total = 0
    for m in payload["models"]:
        hot_cache_size_total += m.get("hot_cache_size_bytes", 0)
        hot_cache_entries_total += m.get("hot_cache_entries", 0)
        hot_cache_max += m.get("hot_cache_max_bytes", 0)
        disk_max = max(disk_max, m.get("max_size_bytes", 0))
    payload["hot_cache_max_bytes"] = hot_cache_max
    payload["hot_cache_size_bytes"] = hot_cache_size_total
    payload["hot_cache_entries"] = hot_cache_entries_total
    payload["disk_max_bytes"] = disk_max

    # Fallback: if no loaded models contributed stats, scan the cache
    # directory directly so the dashboard still shows real disk usage.
    if payload["total_num_files"] == 0 and cache_dir.exists():
        try:
            num_files = 0
            total_bytes = 0
            for subdir in "0123456789abcdef":
                subdir_path = cache_dir / subdir
                if not subdir_path.exists():
                    continue
                for f in subdir_path.glob("*.safetensors"):
                    num_files += 1
                    total_bytes += f.stat().st_size
            payload["total_num_files"] = num_files
            payload["total_size_bytes"] = total_bytes
        except Exception as exc:
            logger.warning("Failed to scan SSD cache directory: %s", exc)

    return payload


@_router.get("/api/stats")
async def get_server_stats(
    model: str = "",
    scope: str = "session",
    is_admin: bool = Depends(require_admin),
):
    """Get server serving stats for the Status dashboard.

    Args:
        model: Filter by model ID. Empty string returns global aggregate.
        scope: "session" for current session, "alltime" for persisted totals.
    """
    from ..server import resolve_model_id
    from ..server_metrics import get_server_metrics

    metrics = get_server_metrics()
    resolved_model = resolve_model_id(model) or model if model else ""
    snapshot = metrics.to_dict()
    if model or scope != "session":
        logger.debug(
            "per-model/scope stats filter requested (model=%r scope=%r) but "
            "ServerMetrics only exposes a global aggregate; returning global snapshot",
            model,
            scope,
        )

    rich = _get_rich_global_settings()
    flat = _get_global_settings()
    host = rich.server.host if rich else "127.0.0.1"
    port = rich.server.port if rich else 8000
    api_key = flat.auth.api_key if flat else ""

    from ..utils.install import get_cli_prefix

    # Build active_models data for the dashboard card.
    active_models_data = _build_active_models_data()
    runtime_cache_data = _build_runtime_cache_observability(
        rich,
        model_filter=model,
    )

    return {
        **snapshot,
        "host": host,
        "port": port,
        "api_key": api_key or "",
        "cli_prefix": get_cli_prefix(),
        "claude_code_context_scaling_enabled": (
            rich.claude_code.context_scaling_enabled if rich else False
        ),
        "claude_code_target_context_size": (
            rich.claude_code.target_context_size if rich else 200000
        ),
        "engines": _get_engine_info(),
        "active_models": active_models_data,
        "runtime_cache": runtime_cache_data,
    }


def _build_active_models_data() -> dict:
    """Build active models status for the dashboard Active Models card."""
    from ..pool.model_discovery import format_size
    from ..prefill_progress import get_prefill_tracker

    engine_pool = _get_engine_pool()
    server_state = _get_server_state()
    if engine_pool is None:
        return {
            "models": [],
            "model_memory_used": 0,
            "model_memory_max": 0,
            "memory_pressure": {
                "enabled": False,
                "current_bytes": 0,
                "soft_bytes": 0,
                "hard_bytes": 0,
                "current_formatted": "0.0GB",
                "soft_formatted": "0.0GB",
                "hard_formatted": "0.0GB",
                "pressure_level": "ok",
            },
            "total_active_requests": 0,
            "total_waiting_requests": 0,
        }

    now = time.monotonic()
    tracker = get_prefill_tracker()
    status = engine_pool.get_status()
    enforcer = (
        getattr(server_state, "process_memory_enforcer", None)
        if server_state is not None
        else None
    )
    enforcer_status = enforcer.get_status() if enforcer is not None else None
    models = []
    total_active = 0
    total_waiting = 0

    for model_info in status.get("models", []):
        if not model_info.get("loaded") and not model_info.get("is_loading"):
            continue

        model_id = model_info["id"]
        active_requests = 0
        waiting_requests = 0
        running_by_id = {}
        waiting_ids = set()
        waiting = []
        activities = []
        # GPU contention / decode-step metrics default before the
        # engine/scheduler branches below may skip assignment (e.g. while
        # a model is still loading and entry.engine is None).
        _contention_detected = False
        _decode_step_time_ms = None
        _decode_step_cv_pct = None

        # Get per-model active/waiting request counts.
        # Follow the same pattern as server.py /api/status endpoint.
        active_request_ids: set = set()
        entry = engine_pool._entries.get(model_id)
        if entry and entry.engine is not None:
            async_core = getattr(entry.engine, "_engine", None)
            if async_core is not None:
                core = getattr(async_core, "engine", None)
                if core is not None:
                    collectors = getattr(core, "_output_collectors", {})
                    try:
                        active_request_ids = set(collectors.keys())
                        active_requests = len(collectors)
                    except RuntimeError:
                        # Scheduler state is mutated from the engine executor;
                        # keep the dashboard endpoint best-effort rather than
                        # failing on a concurrent dict resize.
                        active_request_ids = set()
                        active_requests = len(collectors)

                    sched = getattr(core, "scheduler", None)
                    if sched is not None and hasattr(sched, "snapshot_for_admin"):
                        snap = sched.snapshot_for_admin()
                        running_by_id = snap["running_by_id"]
                        waiting_queue = snap["waiting"]
                        waiting_requests = len(waiting_queue)
                        waiting_ids = {req.request_id for req in waiting_queue}
                        waiting = [
                            {
                                "request_id": req.request_id,
                                "queue_position": idx,
                                "elapsed_seconds": max(0.0, now - req.arrival_time),
                                "prompt_tokens": getattr(req, "num_prompt_tokens", 0),
                            }
                            for idx, req in enumerate(waiting_queue, start=1)
                        ]
                    # Expose GPU contention metrics from scheduler
                    _contention_detected = False
                    _decode_step_time_ms = None
                    _decode_step_cv_pct = None
                    if sched is not None and hasattr(sched, "get_stats"):
                        try:
                            sched_stats = sched.get_stats()
                            _contention_detected = sched_stats.get(
                                "gpu_contention_detected", False
                            )
                            _decode_step_time_ms = sched_stats.get(
                                "decode_step_time_ms"
                            )
                            _decode_step_cv_pct = sched_stats.get("decode_step_cv_pct")
                        except Exception:
                            pass
            elif hasattr(entry.engine, "get_activity_snapshot"):
                snapshot = entry.engine.get_activity_snapshot()
                active_requests = snapshot.get("active_requests", 0)
                activities = snapshot.get("activities", [])
                _contention_detected = False
                _decode_step_time_ms = None
                _decode_step_cv_pct = None

        prefilling = tracker.get_model_progress(model_id)
        prefilling_ids = {p["request_id"] for p in prefilling}

        # Generating = active requests that finished prefill.
        generating = []
        for rid in sorted(active_request_ids - prefilling_ids - waiting_ids):
            req = running_by_id.get(rid)
            generated_tokens = getattr(req, "num_output_tokens", 0) if req else 0
            started_at = getattr(req, "generation_started_at", None) if req else None
            last_activity_at = getattr(req, "last_activity_at", None) if req else None
            elapsed = max(0.0, now - started_at) if started_at else None
            last_activity_age = (
                max(0.0, now - last_activity_at) if last_activity_at else None
            )
            tokens_per_second = (
                generated_tokens / elapsed if elapsed and elapsed > 0 else 0.0
            )
            generating.append(
                {
                    "request_id": rid,
                    "elapsed_seconds": elapsed,
                    "generated_tokens": generated_tokens,
                    "tokens_per_second": tokens_per_second,
                    "last_activity_age_seconds": last_activity_age,
                    "prompt_tokens": getattr(req, "num_prompt_tokens", 0) if req else 0,
                    "max_tokens": getattr(req, "max_tokens", None) if req else None,
                }
            )

        loading_started_at = model_info.get("loading_started_at")
        loading_elapsed_seconds = (
            max(0.0, now - loading_started_at) if loading_started_at else None
        )
        loading_estimated_seconds = None
        loading_remaining_seconds_estimate = None
        if loading_elapsed_seconds is not None:
            estimated_size_gb = model_info.get("estimated_size", 0) / (1024**3)
            # Model loaders do not expose byte-level progress, so use a
            # deliberately conservative elapsed-time estimate and cap below
            # complete until the model is actually loaded.
            observed_seconds_per_gb = status.get("load_seconds_per_gb_estimate")
            observations = status.get("load_time_observations", 0)
            if observed_seconds_per_gb and observations >= 2:
                # Adapt to this machine/session once we have more than a
                # single potentially-misleading sample.
                loading_estimated_seconds = max(
                    3.0,
                    1.0 + estimated_size_gb * float(observed_seconds_per_gb),
                )
                if loading_elapsed_seconds < loading_estimated_seconds:
                    loading_remaining_seconds_estimate = max(
                        0.0, loading_estimated_seconds - loading_elapsed_seconds
                    )

        # Compute idle time and TTL remaining for loaded models.
        is_loaded = (
            model_info.get("loaded") and entry is not None and entry.engine is not None
        )
        last_access = model_info.get("last_access")
        idle_seconds: float | None = None
        ttl_remaining_seconds: float | None = None

        if is_loaded and last_access is not None and last_access > 0:
            idle_seconds = max(0.0, time.time() - last_access)

        # Determine effective TTL: per-model ttl_seconds first, then global idle_timeout.
        effective_ttl: int | None = None
        settings_manager = _get_settings_manager()
        if is_loaded and settings_manager is not None:
            model_settings = settings_manager.get_settings(model_id)
            if (
                model_settings is not None
                and getattr(model_settings, "ttl_seconds", None) is not None
            ):
                effective_ttl = model_settings.ttl_seconds
        if effective_ttl is None:
            global_settings = _get_global_settings()
            if global_settings is not None:
                gt = getattr(global_settings, "idle_timeout", None)
                if gt is not None:
                    effective_ttl = getattr(gt, "idle_timeout_seconds", None)

        if is_loaded and effective_ttl is not None and idle_seconds is not None:
            ttl_remaining_seconds = max(0.0, effective_ttl - idle_seconds)

        models.append(
            {
                "id": model_id,
                "estimated_size": model_info.get("estimated_size", 0),
                "estimated_size_formatted": format_size(
                    model_info.get("estimated_size", 0)
                ),
                "actual_size": model_info.get("actual_size") or 0,
                "actual_size_formatted": (
                    format_size(model_info.get("actual_size", 0))
                    if model_info.get("actual_size")
                    else None
                ),
                "pinned": model_info.get("pinned", False),
                "is_loading": model_info.get("is_loading", False),
                "loading_elapsed_seconds": loading_elapsed_seconds,
                "loading_estimated_seconds": loading_estimated_seconds,
                "loading_remaining_seconds_estimate": loading_remaining_seconds_estimate,
                "active_requests": active_requests,
                "waiting_requests": waiting_requests,
                "waiting": waiting,
                "activities": activities,
                "prefilling": prefilling,
                "generating": generating,
                "idle_seconds": idle_seconds,
                "ttl_remaining_seconds": ttl_remaining_seconds,
                "gpu_contention_detected": _contention_detected,
                "decode_step_time_ms": _decode_step_time_ms,
                "decode_step_cv_pct": _decode_step_cv_pct,
            }
        )

        total_active += active_requests
        total_waiting += waiting_requests

    # model_memory_used reports phys_footprint (whole process) when the
    # enforcer is running so the UI's usage bar matches the value used to
    # drive eviction. model_memory_max is the final_ceiling from
    # enforcer.get_final_ceiling().
    if enforcer_status is not None and enforcer_status.get("enabled"):
        memory_used = enforcer_status.get("current_bytes", 0)
        memory_max = enforcer_status.get("ceiling_bytes", 0)
    else:
        memory_used = status.get("current_model_memory", 0)
        memory_max = status.get("final_ceiling", 0)
    # Aggregate GPU contention across all models
    any_contention = any(m.get("gpu_contention_detected", False) for m in models)
    max_cv = max((m.get("decode_step_cv_pct") or 0.0 for m in models), default=0.0)

    return {
        "models": models,
        "model_memory_used": memory_used,
        "model_memory_max": memory_max,
        "gpu_contention_detected": any_contention,
        "decode_step_cv_pct": round(max_cv, 1),
        "memory_pressure": {
            "enabled": bool(enforcer_status and enforcer_status.get("enabled")),
            "current_bytes": (
                enforcer_status.get("current_bytes", 0)
                if enforcer_status is not None
                else 0
            ),
            "soft_bytes": (
                enforcer_status.get("soft_bytes", 0)
                if enforcer_status is not None
                else 0
            ),
            "hard_bytes": (
                enforcer_status.get("hard_bytes", 0)
                if enforcer_status is not None
                else 0
            ),
            "current_formatted": (
                enforcer_status.get("current_formatted", "0.0GB")
                if enforcer_status is not None
                else "0.0GB"
            ),
            "soft_formatted": (
                enforcer_status.get("soft_formatted", "0.0GB")
                if enforcer_status is not None
                else "0.0GB"
            ),
            "hard_formatted": (
                enforcer_status.get("hard_formatted", "0.0GB")
                if enforcer_status is not None
                else "0.0GB"
            ),
            "pressure_level": (
                enforcer_status.get("pressure_level", "ok")
                if enforcer_status is not None
                else "ok"
            ),
        },
        "total_active_requests": total_active,
        "total_waiting_requests": total_waiting,
    }


@_router.post("/api/stats/clear")
async def clear_server_stats(is_admin: bool = Depends(require_admin)):
    """Clear session server metrics."""
    from ..server_metrics import get_server_metrics

    get_server_metrics().clear_metrics()
    return {"status": "ok"}


@_router.post("/api/stats/clear-alltime")
async def clear_alltime_stats(is_admin: bool = Depends(require_admin)):
    """Clear all-time server metrics and delete persisted stats file."""
    from ..server_metrics import get_server_metrics

    get_server_metrics().clear_alltime_metrics()
    return {"status": "ok"}


def _iter_loaded_schedulers():
    """Yield (model_id, scheduler) for each loaded model.

    Traverses the internal engine hierarchy: pool entry → async engine →
    core engine → scheduler.  Both ``clear_ssd_cache`` and
    ``clear_hot_cache`` share this traversal.
    """
    engine_pool = _get_engine_pool()
    if engine_pool is None:
        return
    for model_info in engine_pool.get_status().get("models", []):
        model_id = model_info.get("id")
        if not model_id or not model_info.get("loaded"):
            continue
        entry = engine_pool._entries.get(model_id)
        if entry is None or entry.engine is None:
            continue
        async_core = getattr(entry.engine, "_engine", None)
        core = getattr(async_core, "engine", None) if async_core is not None else None
        scheduler = getattr(core, "scheduler", None) if core is not None else None
        if scheduler is not None:
            yield model_id, scheduler


@_router.post("/api/ssd-cache/clear")
async def clear_ssd_cache(is_admin: bool = Depends(require_admin)):
    """Clear all SSD cache files for all loaded models.

    Uses loaded models' SSD cache managers when available.  Falls back to
    direct filesystem deletion so caches can be wiped even when no model
    is loaded.
    """
    total_deleted = 0

    for model_id, scheduler in _iter_loaded_schedulers():
        ssd_manager = getattr(scheduler, "paged_ssd_cache_manager", None)
        if ssd_manager is not None:
            try:
                total_deleted += ssd_manager.clear()
            except Exception as exc:
                logger.warning(
                    "Failed to clear SSD cache for model '%s': %s",
                    model_id,
                    exc,
                )

    # Phase 2: remove any remaining files on disk (covers unloaded models)
    global_settings = _get_rich_global_settings()
    if global_settings is not None:
        cache_dir = global_settings.cache.get_ssd_cache_dir(
            global_settings.base_path,
        )
        if cache_dir.exists():
            try:
                for subdir in "0123456789abcdef":
                    subdir_path = cache_dir / subdir
                    if not subdir_path.exists():
                        continue
                    for f in subdir_path.glob("*.safetensors"):
                        try:
                            f.unlink()
                            total_deleted += 1
                        except OSError:
                            pass
            except Exception as exc:
                logger.warning("Failed to clean SSD cache directory: %s", exc)

    return {"status": "ok", "total_deleted": total_deleted}


@_router.post("/api/hot-cache/clear")
async def clear_hot_cache(is_admin: bool = Depends(require_admin)):
    """Clear the in-memory (hot) cache for all loaded models.

    No filesystem fallback needed — hot cache is in-memory only and does
    not survive process restart.
    """
    total_cleared = 0
    for model_id, scheduler in _iter_loaded_schedulers():
        ssd_manager = getattr(scheduler, "paged_ssd_cache_manager", None)
        if ssd_manager is not None and hasattr(ssd_manager, "clear_hot_cache"):
            try:
                total_cleared += ssd_manager.clear_hot_cache()
            except Exception as exc:
                logger.warning(
                    "Failed to clear hot cache for model '%s': %s",
                    model_id,
                    exc,
                )
        rate_tracker = getattr(scheduler, "_cache_rate_tracker", None)
        if rate_tracker is not None:
            rate_tracker.clear()
    return {"status": "ok", "total_cleared": total_cleared}


@_router.post("/api/cache/probe")
async def probe_cache(
    request: CacheProbeRequest,
    is_admin: bool = Depends(require_admin),
):
    """Probe cache state for a chat message list.

    Classifies each block of the rendered prompt into one of three buckets:
    - ``blocks_ssd_hot``: in the SSD manager's hot cache (RAM copy of cold
        blocks, ready to mount without disk read)
    - ``blocks_ssd_disk``: only in the SSD index on disk
    - ``blocks_cold``: not cached anywhere (requires full prefill)

    The split is computed via a walk of the chain-hashed block sequence — the
    same hashing the scheduler uses at prefill time. The model must be loaded
    for the probe to run; unloaded models return ``model_loaded: false``.
    """
    engine_pool = _get_engine_pool()
    if engine_pool is None:
        raise HTTPException(status_code=503, detail="Engine pool not initialized")

    entry = engine_pool._entries.get(request.model_id)
    if entry is None:
        raise HTTPException(
            status_code=404, detail=f"Model not found: {request.model_id}"
        )
    if entry.engine is None:
        return {
            "model_id": request.model_id,
            "model_loaded": False,
            "reason": "Model is not loaded — load it to enable cache probing.",
        }

    engine = entry.engine
    tokenizer = getattr(engine, "_tokenizer", None)
    if tokenizer is None or not hasattr(tokenizer, "apply_chat_template"):
        raise HTTPException(
            status_code=400,
            detail="Model tokenizer does not support chat templating.",
        )

    # Reach into the scheduler to access the prefix index and SSD manager.
    async_core = getattr(engine, "_engine", None)
    core = getattr(async_core, "engine", None) if async_core is not None else None
    scheduler = getattr(core, "scheduler", None) if core is not None else None
    if scheduler is None:
        raise HTTPException(
            status_code=500, detail="Scheduler unavailable for loaded model."
        )

    prefix_cache = getattr(scheduler, "block_aware_cache", None)
    ssd_manager = getattr(scheduler, "paged_ssd_cache_manager", None)
    paged_cache = getattr(scheduler, "paged_cache_manager", None)
    block_size = getattr(
        getattr(scheduler, "config", None), "paged_cache_block_size", 0
    )
    if not block_size and prefix_cache is not None:
        block_size = getattr(prefix_cache, "block_size", 0)
    if not block_size:
        raise HTTPException(
            status_code=500,
            detail="Cache block size unavailable — cache may not be enabled.",
        )

    # Render + tokenize the prompt using the same path as generation so the
    # hashes line up with what the scheduler would produce at prefill.
    try:
        messages = request.messages
        if hasattr(engine, "_preprocess_messages"):
            messages = engine._preprocess_messages(messages)
        try:
            from ..api.tool_calling import convert_tools_for_template  # type: ignore

            template_tools = (
                convert_tools_for_template(request.tools) if request.tools else None
            )
        except Exception:
            template_tools = request.tools or None
        if hasattr(engine, "_apply_chat_template"):
            prompt = engine._apply_chat_template(
                messages,
                template_tools,
                chat_template_kwargs=request.chat_template_kwargs,
            )
        else:
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        token_ids = list(tokenizer.encode(prompt))
    except Exception as exc:
        raise HTTPException(
            status_code=400, detail=f"Failed to tokenize messages: {exc}"
        )

    total_tokens = len(token_ids)
    if total_tokens == 0:
        return {
            "model_id": request.model_id,
            "model_loaded": True,
            "total_tokens": 0,
            "block_size": block_size,
            "total_blocks": 0,
            "blocks_ssd_hot": 0,
            "blocks_ssd_disk": 0,
            "blocks_cold": 0,
            "ssd_hit_tokens": 0,
            "cold_tokens": 0,
        }

    # Compute chain-hashed block sequence.
    from ..cache.paged_cache import compute_block_hash

    model_name = getattr(paged_cache, "model_name", None) if paged_cache else None
    ssd_index = getattr(ssd_manager, "_index", None) if ssd_manager else None
    ssd_hot = getattr(ssd_manager, "_hot_cache", None) if ssd_manager else None

    # The cache is a contiguous prefix (each block chain-hashed from the
    # previous), so we walk block-by-block until the first retrievability
    # miss — after that, every subsequent block is necessarily cold.
    #
    # Ground truth for "cached" in paged-SSD mode is retrievability:
    # hot_cache (RAM copy) OR ssd_index (on disk). BlockAwarePrefixCache's
    # internal prefix index is deliberately NOT consulted — it tracks every
    # hash the scheduler has seen and isn't cleared by clear_ssd_cache(),
    # so relying on it would report false positives after a manual wipe.
    blocks_ssd_hot = 0
    blocks_ssd_disk = 0
    ssd_hit_tokens = 0

    parent_hash = b""
    total_blocks = (total_tokens + block_size - 1) // block_size

    for start in range(0, total_tokens, block_size):
        end = min(start + block_size, total_tokens)
        block_tokens = token_ids[start:end]
        if not block_tokens:
            break

        block_hash = compute_block_hash(
            parent_hash,
            block_tokens,
            extra_keys=None,
            model_name=model_name,
        )
        parent_hash = block_hash

        in_ssd_hot = ssd_hot is not None and block_hash in ssd_hot
        in_ssd_disk = False
        if ssd_index is not None:
            try:
                in_ssd_disk = ssd_index.contains(block_hash)
            except Exception:
                in_ssd_disk = False

        if not (in_ssd_hot or in_ssd_disk):
            break

        if in_ssd_hot:
            blocks_ssd_hot += 1
        else:
            blocks_ssd_disk += 1
        ssd_hit_tokens += len(block_tokens)

    cached_blocks = blocks_ssd_hot + blocks_ssd_disk
    blocks_cold = max(total_blocks - cached_blocks, 0)

    return {
        "model_id": request.model_id,
        "model_loaded": True,
        "total_tokens": total_tokens,
        "block_size": block_size,
        "total_blocks": total_blocks,
        "blocks_ssd_hot": blocks_ssd_hot,
        "blocks_ssd_disk": blocks_ssd_disk,
        "blocks_cold": blocks_cold,
        "ssd_hit_tokens": ssd_hit_tokens,
        "cold_tokens": max(total_tokens - ssd_hit_tokens, 0),
    }


router = _router
